// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7RhnSDiVUl0pULo7Re9Rw4lWSra4iqfg',
    appId: '1:178952417944:web:0d1f58870c3232f1f0d6ed',
    messagingSenderId: '178952417944',
    projectId: 'languagehungry',
    authDomain: 'languagehungry.firebaseapp.com',
    storageBucket: 'languagehungry.firebasestorage.app',
    measurementId: 'G-ZGW8SLVE56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCya7nIiY3omUzAkETPG_yCZUPRMmbB99Q',
    appId: '1:178952417944:android:ad6db67865661767f0d6ed',
    messagingSenderId: '178952417944',
    projectId: 'languagehungry',
    storageBucket: 'languagehungry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnQb5pw5Jb0miVXJ0DXXMbJhQE89Rf47c',
    appId: '1:178952417944:ios:635f164a072788d3f0d6ed',
    messagingSenderId: '178952417944',
    projectId: 'languagehungry',
    storageBucket: 'languagehungry.firebasestorage.app',
    iosBundleId: 'com.example.langgry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnQb5pw5Jb0miVXJ0DXXMbJhQE89Rf47c',
    appId: '1:178952417944:ios:635f164a072788d3f0d6ed',
    messagingSenderId: '178952417944',
    projectId: 'languagehungry',
    storageBucket: 'languagehungry.firebasestorage.app',
    iosBundleId: 'com.example.langgry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7RhnSDiVUl0pULo7Re9Rw4lWSra4iqfg',
    appId: '1:178952417944:web:3c7aaac69c5e8fd6f0d6ed',
    messagingSenderId: '178952417944',
    projectId: 'languagehungry',
    authDomain: 'languagehungry.firebaseapp.com',
    storageBucket: 'languagehungry.firebasestorage.app',
    measurementId: 'G-X483Z8ZN5P',
  );
}
